### ISSUE TITLE
InGameOverlay is not a standard plugin.

### ISSUE THREAD

**Issue by LargeJojoMAn** [OsuSync/IngameOverlay#5]
I have installed (or attempted to install) the Ingameoverlayplugin, and I succeeded for a short while. I went through the whole process to install it, up until I attempted to change the configuration in Sync to mmf-split. I then noticed that the plugin was never truly installed because of this message that was in the start up lines:

IngameOverlayPlugin not a standard plugin (Can't install dependency plugin: 7216787b-507b-4eef-96fb-e993722acf2e, version ^1.4.3)
[4:27:28 AM]    at Sync.Plugins.PluginManager.CheckGUIDUpdate(SyncPluginDependency item)
   at Sync.Plugins.PluginManager.layerLoader(IList`1 asmList)

I'm not sure how to go about this issue, because I have gone through and updated everything and retried installing it numerous times, each time unsuccessful. I realize that this issue is pretty vague, and I am sorry about that, but I hope that there will be salvation for this yet, as I have never been able to get an ingameoverlay ever since I tried before and completely deleted all files concerning it.

**Comment by Deliay** [comment]
try 'plugins install 7216787b-507b-4eef-96fb-e993722acf2e' in command line

**Comment by Deliay** [comment]
it caused by auto download dependencies failed, transfer to Sync repo.
